ci: fix postgres error fresh import, see below [skip ci]
    git@vps76:~/repos/continuwuity$ .github/actions/postgres/import_history.sh
    ✓ No ledger directory provided. Cloning _metadata/badges branch from https://github.com/gamesguru/continuwuity.git...
    ✓ Applying fresh schema from .github/actions/postgres/tables.sql...
    NOTICE:  drop cascades to view v_run_regressions
    NOTICE:  table "master_baseline" does not exist, skipping
    psql:.github/actions/postgres/tables.sql:5: NOTICE:  view "v_run_regressions" does not exist, skipping
    ✓ Starting bulk historical JSON import into 'c10y'...
    → Ingesting run summaries...
    CREATE TABLE
    COPY 3365
    INSERT 0 3360
    → Consolidating and ingesting test details...
    CREATE TABLE
    COPY 1974162
    ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
    HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    ✓ Bulk import complete.